CREATE TABLE userresources_temp AS SELECT *
                                          FROM userresources;

DROP TABLE userresources;

CREATE TABLE userresources (
    id              VARCHAR (64)  PRIMARY KEY
                                  NOT NULL,
    tb_id           VARCHAR (20),
    tb_name         VARCHAR (200),
    keywords        VARCHAR (128),
    resume          VARCHAR (200),
    title           VARCHAR (128),
    year            INTEGER,
    dzwjlx          VARCHAR (10),
    dzwjlx_name     VARCHAR (20),
    zylx            VARCHAR (10),
    zylx_name       VARCHAR (20),
    yhlx            VARCHAR (10),
    mtgslx          VARCHAR (10),
    source_app      VARCHAR (32),
    ori_tree_code   VARCHAR (32),
    ori_tree_name   VARCHAR (32),
    ori_tree_pos    VARCHAR (64),
    s_edu_code      VARCHAR (40),
    file_path       VARCHAR (128),
    file_format     VARCHAR (10),
    file_size       INTEGER,
    file_md5        VARCHAR (40),
    range_type      VARCHAR (2),
    s_state         INTEGER       DEFAULT ('100'),
    s_creator       VARCHAR (64),
    s_creator_name  VARCHAR (100),
    s_create_time   VARCHAR (32),
    s_modifier      VARCHAR (64),
    s_modifier_name VARCHAR (100),
    s_modify_time   VARCHAR (32),
    page_num        INTEGER,
    fullpath        VARCHAR (256),
    groupids        VARCHAR (256),
    rkxd            VARCHAR (2),
    nj              VARCHAR (2),
    zxxkc           VARCHAR (2),
    fascicule       VARCHAR (2),
    ex1             VARCHAR (200),
    ex2             VARCHAR (200),
    ex3             VARCHAR (200),
    ex4             VARCHAR (200),
    ex5             VARCHAR (200),
    ex_zynrlx       VARCHAR (10),
    ex_zynrlx_name  VARCHAR (64),
    pos_type        INTEGER,
    sourcePath      VARCHAR (128),
    pvt_biz_type    VARCHAR (10)  DEFAULT ('0') 
);

INSERT INTO userresources (
                              id,
                              tb_id,
                              tb_name,
                              keywords,
                              resume,
                              title,
                              year,
                              dzwjlx,
                              dzwjlx_name,
                              zylx,
                              zylx_name,
                              yhlx,
                              mtgslx,
                              source_app,
                              ori_tree_code,
                              ori_tree_name,
                              ori_tree_pos,
                              s_edu_code,
                              file_path,
                              file_format,
                              file_size,
                              file_md5,
                              range_type,
                              s_state,
                              s_creator,
                              s_creator_name,
                              s_create_time,
                              s_modifier,
                              s_modifier_name,
                              s_modify_time,
                              page_num,
                              fullpath,
                              groupids,
                              rkxd,
                              nj,
                              zxxkc,
                              fascicule,
                              ex1,
                              ex2,
                              ex3,
                              ex4,
                              ex5,
                              ex_zynrlx,
                              ex_zynrlx_name,
                              pos_type,
                              sourcePath
                          )
                          SELECT id,
                                 tb_id,
                                 tb_name,
                                 keywords,
                                 resume,
                                 title,
                                 year,
                                 dzwjlx,
                                 dzwjlx_name,
                                 zylx,
                                 zylx_name,
                                 yhlx,
                                 mtgslx,
                                 source_app,
                                 ori_tree_code,
                                 ori_tree_name,
                                 ori_tree_pos,
                                 s_edu_code,
                                 file_path,
                                 file_format,
                                 file_size,
                                 file_md5,
                                 range_type,
                                 s_state,
                                 s_creator,
                                 s_creator_name,
                                 s_create_time,
                                 s_modifier,
                                 s_modifier_name,
                                 s_modify_time,
                                 page_num,
                                 fullpath,
                                 groupids,
                                 rkxd,
                                 nj,
                                 zxxkc,
                                 fascicule,
                                 ex1,
                                 ex2,
                                 ex3,
                                 ex4,
                                 ex5,
                                 ex_zynrlx,
                                 ex_zynrlx_name,
                                 pos_type,
                                 sourcePath
                            FROM userresources_temp;

DROP TABLE userresources_temp;